[블랙잭 게임 1단계] 리뷰 요청 드립니다.
kiworkshop/java-blackjack pull request #2
Opened 2021-07-29 11:10 UTC by jiwoo-kimm

# STUDYLOG

## Run Test with Coverage

- `Intellij`에서 `Run Test With Coverage`를 수행하면 테스트의 코드 커버리지를 파악할 수 있다.

<br>

## 방어 생성자

- 의도치 않은 인스턴스 생성을 명시적으로 차단하기 위해 접근제어자가 `private`인 생성자를 만들면 안전하다.
- 컴파일러가 자동으로 `public` 기본 생성자를 만들기 때문에 명시적으로 방어를 해야 객체 생성을 차단할 수 있다.
- 유틸리티 클래스, 즉 도구용 클래스에 주로 사용된다.
- [[이펙티브 자바] Item4- 인스턴스화를 막으려거든 private 생성자를 사용하라](https://jjingho.tistory.com/46)

<br>

## `Collections.singletonList()` vs `Arrays.asList()`

||`Collections.singletonList()`|`Arrays.asList()`|
|--|--|--|
|인자와 리턴값|단일 객체를 원소로 갖는 `List`를 반환한다.|배열을 `List`로 변환한다.|
|속도|배열 변환의 과정이 없어서 보다 빠르다.||
|`List` size|불변|불변|
|원소 객체의 주소값|불변|불변|
|원소 객체의 속성|불변|가변|

- [Collections (Java Platform SE 8)](https://docs.oracle.com/javase/8/docs/api/java/util/Collections.html#singletonList-T-)
- [[Java] Arrays.asList() vs Collections.singletonList()](https://livenow14.tistory.com/42)

<br>

## `Predicate<T>`의 `neagte()`
- predicate의 logical negation을 수행한 값을 반환한다.
- [Predicate (Java Platform SE 8)](https://docs.oracle.com/javase/8/docs/api/java/util/function/Predicate.html)
- [java8-default-method](https://gist.github.com/ihoneymon/3a98ea468766d6ff3678)

2021-07-30 22:49 UTC, wbluke requested changes
멋진 코드 잘 봤습니다 !
테스트도 깔끔하게 작성해 주셨고, 흐름 읽기도 편했네요 ㅎㅎ
보면서 몇 가지 수정해보면 좋을 사항들 코멘트 남겼으니 확인 부탁드려요 🙂

2021-07-30 22:49 UTC, wbluke commented on README.md
> +
아주 꼼꼼하게 작성해주셨네요 ㅎㅎ 💯

2021-07-30 22:49 UTC, wbluke commented on src/main/java/blackjack/BlackjackApplication.java
> +            System.out.println(e.getMessage());
관점 차이일 수 있겠으나, 예외를 어떻게 처리하고 다룰지에 대한 관심사는 Controller가 담당해야 하지 않을까 싶어요 ㅎㅎ
Controller 입장에서 보면 예외가 어떻게 발생하든 책임지지 않는 (핸들링할 수 없는) 형태라서요 :)

2021-07-30 22:49 UTC, wbluke commented on src/main/java/blackjack/view/InputView.java
> +        Scanner scanner = new Scanner(System.in);
InputView의 정적 메서드를 호출할 때마다 Scanner 객체를 매번 생성하겠네요 ! :)

2021-07-30 22:49 UTC, wbluke commented on src/main/java/blackjack/domain/card/AceCard.java
> +    public static final String SIGNATURE = "A";
내부에서만 쓰이는 상수라면 private 제어자로 선언하는 것이 좋겠어요 ㅎㅎ
근데 아마 IDE 단축키 default 설정이 public 이라서 그럴 것 같은데요,
상수 추출 단축키를 연속으로 두번 누르면 접근제어자 설정 창이 나오니 private 으로 설정해보면 좋겠습니다 :)

2021-07-30 22:49 UTC, wbluke commented on src/main/java/blackjack/domain/game/Deck.java
> +        generateCards();
void 형태는 아무래도 반환형이 있는 메서드보다 의미가 불명확할 수 있는데요 ㅎㅎ
(public 메서드라면 테스트하기 어려운 구조기도 하고요)
요렇게 해도 되겠네요 :)
```java
this.cards = generateCards();
```

2021-07-30 22:49 UTC, wbluke commented on src/main/java/blackjack/domain/game/Deck.java
> +    }
요 메서드를 보고나서 드는 생각을 정리해 볼게요 ㅎㅎ
- 카드뭉치인 Deck에서 Hands를 알아야 할 필요가 있을까?
- 외부에서 카드를 `몇 장 뽑을지` 를 전달해주는 형식이면, 2개의 메서드를 통합할 수 있지 않을까? 
  - 테스트도 현재는 2라는 상수를 사용해서 테스트하고 있는데, 원하는 형태로 개수를 지정해서 체크할 수 있지 않을까?

2021-07-30 22:49 UTC, wbluke commented on src/main/java/blackjack/domain/game/Deck.java
> +                .forEach(n -> deals.add(draw()));
전체적으로 반복이 필요한 부분에서 IntStream.range() 구문을 많이 사용하셨는데요
복잡한 가공이 아닌 이상 단순 반복문(for-i, iter)이 가독성이 더 좋을 수 있습니다 :)

2021-07-30 22:49 UTC, wbluke commented on src/main/java/blackjack/domain/game/Deck.java
> +        Collections.shuffle(cards);
이 부분 때문에 개수 체크 테스트밖에 할 수 없는 구조인데요 (많이 이야기했던 테스트하기 어려운 부분이죠?)
Deck을 한 단계 추상화시켜서 프로덕션 코드에서는 Random으로 섞인 Deck을 사용하고, 테스트에서는 테스트용 Deck을 사용하도록 개선해보면 어떨까요?
그러면 테스트 쪽에서는 원하는 카드를 Deck에 넣고 실제 카드 검증까지 진행해볼 수 있을 것 같아요 :)

2021-07-30 22:49 UTC, wbluke commented on src/main/java/blackjack/domain/participant/Participant.java
> +public class Participant {
Participant가 인터페이스면 어떨까요?
상위 클래스가 구체 클래스인 경우, 상속 구조인지를 알기가 힘들어요 :)

2021-07-30 22:49 UTC, wbluke commented on src/main/java/blackjack/view/OutputView.java
> +        playersPrize.getPlayerPrizes().forEach(playerPrize -> System.out.printf("%s: %s%n", playerPrize.getPlayerName(), playerPrize.getPrize().getTitle()));
```java
playerPrize.getPrize().getTitle()
```
보통 객체를 포장할 경우 디미터법칙을 위반하는 요런 모양이 많이 나오는데요 ㅎㅎ
playerPrize 쪽에서 바로 text를 반환하도록 하면 어떨까요?
Prize를 외부에서 알 필요가 없을 것 같아요 :)

2021-07-30 22:49 UTC, wbluke commented on src/main/java/blackjack/domain/participant/Players.java
> +    private final List<Player> players;
일급컬렉션을 만들어주셨는데 특별히 하는 일이 없네요 ㅎㅎ
일급컬렉션이 담당해야 하는데 놓친 역할(player list에 대한 가공 로직 등)이 있는지 체크해주시고, 없다면 없애도 될 것 같아요 :)

2021-07-30 22:49 UTC, wbluke commented on src/main/java/blackjack/domain/prize/PrizeResults.java
> +        }
bust()와 blackjack()이 둘 다 boolean 반환인데, 의미가 더 명확한 상태 Enum을 만들어서 관리해보면 어떨까요? :)

2021-07-30 22:49 UTC, wbluke commented on src/main/java/blackjack/service/BlackjackService.java
> +    public ParticipantsDto getParticipants() {
DTO로 소통하는 것 좋네요 :)

2021-08-01 02:31 UTC, jiwoo-kimm commented on src/main/java/blackjack/BlackjackApplication.java
> +            System.out.println(e.getMessage());
아 네 그렇네요! 예외를 Controller가 잡아서 출력하도록 수정했습니다.

2021-08-01 02:44 UTC, jiwoo-kimm commented on src/main/java/blackjack/view/InputView.java
> +        Scanner scanner = new Scanner(System.in);
앗 리팩토링할 때 놓친 것 같습니다ㅎㅎ; Scanner도 정적으로 선언해서 재사용할 수 있도록 수정했습니다!

2021-08-01 02:47 UTC, jiwoo-kimm commented on src/main/java/blackjack/domain/card/AceCard.java
> +    public static final String SIGNATURE = "A";
앗 넵! 원래 AceCard 메서드를 외부에서도 호출하는 부분이 있었는데, AceCard 안으로 메서드를 옮길 때 접근제어자를 수정하는 걸 깜빡했습니다. 수정했습니다!

2021-08-01 02:52 UTC, jiwoo-kimm commented on src/main/java/blackjack/domain/game/Deck.java
> +        generateCards();
넵! 저희는 멤버 변수에 직접 접근해서 카드를 추가할 수 있으니 따로 ArrayList를 만들어서 넘겨줄 필요가 없다고 생각해서 저렇게 했던 건데, void 리턴 형태는 지양하는 게 더 중요한가 보네요..!

2021-08-01 02:56 UTC, jiwoo-kimm commented on src/main/java/blackjack/domain/game/Deck.java
> +                .forEach(n -> deals.add(draw()));
IntStream이 이번에 새로 알게 된 방식이라 여러 곳에서 사용해봤는데, for-i를 더 많이 사용하나보네요!
단순 작업 반복문에서는 for-i문을 사용하도록 수정했습니다.

2021-08-01 06:15 UTC, jiwoo-kimm commented on src/main/java/blackjack/domain/game/Deck.java
> +    }
- Hands가 아니라 그냥 가지고 있는 카드를 List로 반환하도록 수정해서 Hands와 Deck의 결합도를 낮췄습니다.
- 메서드 두 개를 하나로 통합하기 위해, 뽑을 개수를 파라미터로 받아서 카드를 뽑는 것으로 수정했습니다. `drawCard()`는 아예 private으로 외부의 접근을 막고, `drawCards()`에서 내부적으로 호출하도록 수정했습니다. 그리고 리턴값이 `Card`에서 `List<Card>`로 변함에 따라, 관련 `take()` 메서드도 모두 같이 수정했습니다.

선생님 그런데 고치면서 궁금한 점이 생겼는데요, 사실 블랙잭에서 initial deal 이후에는, Card를 뽑고 플레이어가 take하는 로직이  모두 1장 단위로만 이루어집니다. 그래서 사실 여러 장 뽑는 메서드만 노출시키면, 카드 한 장도 항상 List로 래핑해서 전달하게 되는데요, 이 작업이 오히려 비효율적이지는 않나요?

2021-08-01 06:32 UTC, jiwoo-kimm commented on src/main/java/blackjack/view/OutputView.java
> +        playersPrize.getPlayerPrizes().forEach(playerPrize -> System.out.printf("%s: %s%n", playerPrize.getPlayerName(), playerPrize.getPrize().getTitle()));
아 넵 그러네요! 수정했습니다

2021-08-01 06:40 UTC, jiwoo-kimm commented on src/main/java/blackjack/domain/participant/Players.java
> +    private final List<Player> players;
사실 Players 안에서 각 플레이어의 hitOrStand를 한 번에 처리하고 싶었는데, 그게 View의 입출력과 연관이 깊게 되어있다 보니 Players 클래스 안까지 끌고 오지 않았거든요! 그래서 지금 역할이 딱히 없어졌네요.. 일단 없애겠습니다!

2021-08-01 07:44 UTC, jiwoo-kimm commented on src/main/java/blackjack/domain/prize/PrizeResults.java
> +        }
넵 `Status`를 Enum으로 만들어서 관리하도록 수정했습니다!

2021-08-01 08:26 UTC, jiwoo-kimm commented on src/main/java/blackjack/domain/participant/Participant.java
> +public class Participant {
Participant를 추상 클래스로 구현하도록 수정했는데, 이렇게 하면 어떤가요..?
저는 Participant를 인스턴스화 하는 것을 막으면서도, 공통된 필드와 이를 활용한 기능(코드가 완전히 동일)을 제공하기 때문에 인터페이스보다 추상클래스가 더 효율적이라는 생각이 드는데, 여전히 인터페이스를 사용해야 할 이유가 있다면 설명 부탁드려도 될까요?

2021-08-01 16:44 UTC, jiwoo-kimm commented on src/main/java/blackjack/domain/game/Deck.java
> +        Collections.shuffle(cards);
넵! 전략 패턴을 사용해서 Table과 Deck이 생성자에서 DeckGenerator를 받고, 전략에 따라서 카드들을 생성하도록 수정했습니다! 관련 테스트들도 함께 수정했는데, 이 정도면 검증이 충분할까요?

2021-08-02 09:58 UTC, wbluke commented on src/main/java/blackjack/domain/participant/Status.java
> +public enum Status {
이름이 좀 더 구체적이면 좋을 것 같아요 ㅎㅎ 
`Status`는 아주 general한 범위라서 어떤 상태를 말하는지 모를 것 같아요 :)

2021-08-02 09:58 UTC, wbluke commented on src/main/java/blackjack/domain/participant/Status.java
> +        if (participant.countAceCards() == 1 && participant.countMajorCards() == 1) {
ACE 카드가 한장 & 메이저 카드가 한장 인지를 외부에서 체크하지 말고 Participant(혹은 Hands)에 메세지를 보내서 해결해보면 어떨까요? ㅎㅎ
공개 API를 열어줌으로써 추상화된 의미를 부여할 수도 있겠네요 :)

2021-08-02 09:58 UTC, wbluke commented on src/main/java/blackjack/domain/participant/Participant.java
> +public abstract class Participant {
> Participant를 추상 클래스로 수정했는데, 이렇게 하면 어떤가요..?
저는 Participant를 인스턴스화 하는 것을 막으면서도, 공통된 필드와 이를 활용한 기능(코드가 완전히 동일)을 제공하기 때문에 인터페이스보다 추상클래스가 더 효율적이라는 생각이 드는데, 여전히 인터페이스를 사용해야 할 이유가 있다면 설명 부탁드려도 될까요?

좋은 접근입니다 ㅎㅎ
저도 둘 다 말씀드리려다가, 인터페이스와 추상클래스 중 일반적으로는 인터페이스가 더 유연한 구조이기 때문에 인터페이스만 언급했는데요, 리팩토링 잘 해주신 것처럼 인터페이스로 고민해보시고 추상클래스로 변경하는 행보를 기대해 보았습니다 :) 👍 
(모임 때 말씀드렸듯이 중복되는 로직이 많고 확실하게 상속 구조다! 라는 판단이 들 때만 상속 구조를 사용하시는 것이 좋습니다 ㅎㅎ
저도 Dealer와 Player는 추상클래스 상속 구조로 만들었을 것 같네요)

2021-08-02 09:58 UTC, wbluke commented on src/main/java/blackjack/domain/game/Deck.java
> +    }
아하 넵 그러네요. 제가 통합이라는 용어를 써놓고, 막상 한편으로는 한 장 뽑는 draw() 메서드도 공개해도 된다고 생각했어요 ㅎㅎ
메서드 하나로만 하면 항상 List 형태여서 불편하겠네요.
제가 초점을 맞춘 부분은 초기 드로우 때 `2`장 이라는 숫자를 Deck에서 고정해서 알고 있을 필요가 없지 않을까? 하는 생각 때문이었어요 :)

2021-08-02 10:04 UTC, wbluke approved these changes
지우 선생님 잘 반영해 주셨네요 👍 
남겨주신 질문에 대한 답을 포함하여 소소한 코멘트 조금 더 드렸습니다.
다음 단계 진행하시면서 같이 확인 부탁드려요 🙂

2021-08-02 10:04 UTC, wbluke commented on src/main/java/blackjack/domain/game/Deck.java
>      private final List<Card> cards;
모임 때 이야기 나온 것처럼 Stack 자료구조를 사용하면 밑에서 remove 하는 로직이 없어도 되겠네요 :)

2021-08-02 10:04 UTC, wbluke commented on src/main/java/blackjack/domain/prize/PrizeResults.java
> +        if (dealerStatus == BLACKJACK || playerStatus == BLACKJACK) {
Enum에다가 메시지를 던지도록 하면 어떨까요?
`dealerStatus.isBust()`
`dealerStatus.isBlackJack()`

다만 이런 형태는 status가 null인 경우에 대해 민감하게 반응해야 하긴 합니다.
(물론 지금 구조에서도 status가 null인 경우 분기가 어디로 빠지는지도 같이 체크해야하는 건 동일하지만요 :) )

2021-08-02 10:04 UTC, wbluke commented on src/main/java/blackjack/domain/prize/PrizeResults.java
> +        if (dealer == BUST && player == BUST) {
파라미터명이 `dealerStatus`, `playerStatus` 가 좋겠네요 :)

2021-08-02 10:14 UTC, closed without merging

2021-08-02 13:47 UTC, jiwoo-kimm commented on src/main/java/blackjack/domain/game/Deck.java
> +    }
아 넵ㅎㅎ count를 받아서 카드를 빼주는 부분도 유지하고, 한 장씩 뽑아서 받는 메서드도 추가해서 수정했습니다!

2021-08-02 13:54 UTC, jiwoo-kimm commented on src/main/java/blackjack/domain/participant/Status.java
> +public enum Status {
아 네 그러네요! 패 상태를 알려 주는 역할이니까 `HandsStatus`로 수정했습니다!

2021-08-02 14:08 UTC, jiwoo-kimm commented on src/main/java/blackjack/domain/participant/Status.java
> +        if (participant.countAceCards() == 1 && participant.countMajorCards() == 1) {
앗 이거 저도 생각했던 부분인데, 한 가지 고민했던 부분이 있어요!
`Participant`가 `isBlackjack()` 메서드를 가지고 `HandsStatus`가 이것만 호출하려면, `Participant`가 `BLACKJACK`이라는 `HandsStatus`에 대한 조건을 알아야 하잖아요? 저는 `Participant`가 아니라 `HandsStatus`가 에이스 카드 1장 메이저 카드 1장이라는 조건을 알아야 한다고 생각을 해서, `Participant`한테는 그 카드의 개수들만 물어보도록 했거든요...! 확실히 `Participant`에서 추상화된 메서드를 갖고 있는 게 코드 읽기에는 더 수월하긴 한데, 조건을 확인하는 위치가 `Participant`여도 괜찮은 건가요??

2021-08-02 14:10 UTC, jiwoo-kimm commented on src/main/java/blackjack/domain/participant/Participant.java
> +public abstract class Participant {
아 넵ㅎㅎ 앞으로도 인터페이스로 먼저 공통 기능을 뺀 후에 구현 내용을 보고, 확실히 상속 구조인 경우에만 추상 클래스를 활용해보겠습니닷

2021-08-02 14:17 UTC, jiwoo-kimm commented on src/main/java/blackjack/domain/prize/PrizeResults.java
> +        if (dealer == BUST && player == BUST) {
옙 그러네요 수정했습니다!

2021-08-02 14:21 UTC, jiwoo-kimm commented on src/main/java/blackjack/domain/prize/PrizeResults.java
> +        if (dealerStatus == BLACKJACK || playerStatus == BLACKJACK) {
넵! 해당 메서드 만들어서 활용하도록 수정했습니다.

혹시 null인 경우는 어디서 발생할 수 있을까요?
`HandsStatus.of(participant)` 메서드에서는 bust나 blackjack이 아니면 다 hold를 반환하게 되어있는데, null일 수가 있는 건가요??

2021-08-02 14:47 UTC, jiwoo-kimm commented on src/main/java/blackjack/domain/game/Deck.java
>      private final List<Card> cards;
넵! 스택을 사용했더니 솔라린트가 덱을 쓰라고 해서, 덱에서 pop하도록 구현했습니다

2021-08-03 10:06 UTC, wbluke commented on src/main/java/blackjack/domain/prize/PrizeResults.java
> +        if (dealerStatus == BLACKJACK || playerStatus == BLACKJACK) {
아 현재 상황에서 null이 발생한다는 의미는 아니었고, 어떤 Enum에서 enum.isStatus() 와 같은 형태의 메서드를 만들 때 Enum이 null이 될 수 있는 경우를 고려해야한다는 의미였어요 :)

2021-08-03 10:26 UTC, wbluke commented on src/main/java/blackjack/domain/participant/Status.java
> +        if (participant.countAceCards() == 1 && participant.countMajorCards() == 1) {
오 넵 동의합니다. 제가 의도한 부분은 blackjack 의 의미를 담기 보다는 `participant.hasOneAceCard()` 와 같은 형태로 추상화할 수 있지 않을까 한거였어요 :)

2021-08-03 13:36 UTC, jiwoo-kimm commented on src/main/java/blackjack/domain/participant/Status.java
> +        if (participant.countAceCards() == 1 && participant.countMajorCards() == 1) {
아하 넵! 그렇게 추상화 할 수 있겠네요! 2단계 때 같이 반영하겠습니다~

2021-08-03 13:41 UTC, jiwoo-kimm commented on src/main/java/blackjack/domain/prize/PrizeResults.java
> +        if (dealerStatus == BLACKJACK || playerStatus == BLACKJACK) {
아아 넵! null인 경우도 잘 커버하도록 리팩토링해보겠습니다..!