Step1
kiworkshop/java-blackjack pull request #3
Opened 2021-07-29 11:45 UTC by pageprologue

## 학습로그
##### 1. instanceof vs isInstance()
  - [instanceof vs isInstance()](https://livenow14.tistory.com/36 )
    - instanceof는 컴파일타임에 타입 에러를 체크하고, isInstance()는 런타임에 타입 에러를 체크 한다.
___
##### 2. neagte
  - [Predicate의 결합](https://velog.io/@malgo/%EC%9E%90%EB%B0%94%EC%9D%98-%EC%A0%95%EC%84%9D-%EA%B8%B0%EC%B4%88%ED%8E%B8-Chapter-14-Predicate%EC%9D%98-%EA%B2%B0%ED%95%A9.-CF%EC%99%80-%ED%95%A8%EC%88%98%ED%98%95-%EC%9D%B8%ED%84%B0%ED%8E%98%EC%9D%B4%EC%8A%A4)
    - 	and(), or(), negate()로 두 Predicate를 하나로 결합한다. (default 메서드)

2021-07-30 17:25 UTC, Deocksoo requested changes
희진선생님 안녕하세요, 
구현해주신 내용 잘 읽어보았어요. 코드도 간결하고, 테스트도 꼼꼼하게 작성해주셔서 읽기 좋은 코드네요 👍 
기본적인 자바 convention 이나 프로그래밍 요구사항에 따른 코드 작성, layer 구분과 같은 부분들도 이제 많이 익숙하신 것 같아서,
상속이나 조합과 같은 객체 사이의 관계를 중심으로 코멘트 조금 남겨보았어요. 
확인 한 번 부탁드려요 :)

2021-07-30 17:25 UTC, Deocksoo commented on src/main/java/blackjack/domain/game/Table.java
> +public class Table {
지금 Table에서 하는 일들을 살펴보면 Deck, Dealer, Players들이 하는 일들을 각각 따로 Delegate 해 주는 정도의 역할을 하고 있는 듯 하네요. Deck, Dealer, Players 세 객체의 조합(composition)을 이용해 Table을 구성한 이유는 무엇인가요?

2021-07-30 17:25 UTC, Deocksoo commented on src/main/java/blackjack/domain/game/Hands.java
> +    private final List<Card> hands;
일급컬렉션 내부의 java collection 이름이 반드시 일급컬렉션 이름과 같아야 할 필요는 없겠죠 :)
혹자는 가급적이면 다르게 짓는 것이 좋다는 이야기를 하기도 하구요.
hands는 카드들을 지칭하는 것 같은데, 의미에 맞게 변수 명을 지어주는 것은 어떤가요?

2021-07-30 17:25 UTC, Deocksoo commented on src/main/java/blackjack/domain/card/Card.java
> +    private final String signature;
숫자나 J, Q, K 값이군요. Enum으로 관리해보는 것은 어떤가요?

2021-07-30 17:25 UTC, Deocksoo commented on src/main/java/blackjack/domain/card/AceCard.java
> +public class AceCard extends Card {
AceCard는 Card 로서 사용되는 경우가 없는 것 같은데요. Card를 extends 하신 이유는 무엇인가요?

2021-07-30 17:25 UTC, Deocksoo commented on src/main/java/blackjack/domain/game/Hands.java
> +                .filter(((Predicate<? super Card>) AceCard.class::isInstance).negate())
아하. AceCard를 Card를 상속받아 만든 이유가 이것이군요. class 타입으로 AceCard를 구분하지 말고, card에게 메시지를 던져 물어보고 판단하면 어떤가요? 그러면 불필요한 상속을 하지 않아도 될 것 같네요.

2021-07-30 17:25 UTC, Deocksoo commented on src/main/java/blackjack/domain/participant/Dealer.java
> +public class Dealer extends Participant {
Player와 함께 Participant를 상속받고 있군요. 아마도 Participant의 기능을 그대로 이용하기 위해 상속받으신 것 같은데요, 타입의 관점에서 보았을 때에는 Participant를 상속받는 의미가 별로 없는 것으로 보여요. 구체적으로 이야기하면, dealer.take(card), player.take(card)와 같이 Player, Dealer 타입을 사용처에서 직접 사용하고 있고, 해당 타입을 통해 participant의 메서드들을 호출하고 있지요. Dealer, Player를 Participant로서 추상화해서 사용하고 있지는 않아요. 
단지 기능을 이용하기 위해서라면 굳이 상속을 받지 않아도 괜찮을 것 같은데, composition을 활용해보는 것은 어떤가요? 혹은 상속을 받는다면 Player와 Dealer를 Participant로서 추상화해서 사용해보는 것은 어떤가요? 
아마도 후자가 구현하기에는 훨씬 난이도가 높을 수 있으니(혹은 상황에 따라 추상화가 어려울수도 있죠), 고려해서 고민해보시면 좋을 것 같네요 :)

2021-08-30 12:45 UTC, pageprologue commented on src/main/java/blackjack/domain/game/Hands.java
> +    private final List<Card> hands;
넵 변수 명을 cards로 변경하였습니다~!

2021-08-30 12:46 UTC, pageprologue commented on src/main/java/blackjack/domain/card/Card.java
> +    private final String signature;
넵 말씀하신 대로 카드를 Enum 객체로 따로 만들었습니다~!

2021-08-30 12:48 UTC, pageprologue commented on src/main/java/blackjack/domain/card/AceCard.java
> +public class AceCard extends Card {
아래에 말씀해 주신것 같이 ACE 카드가 1또는 11로 계산될 수 있어서 객체로 빼서 상속 받도록 하였는데요~ 이 부분은 전체 카드를 Enum으로 관리하도록 수정하였습니다~!

2021-08-30 12:50 UTC, pageprologue commented on src/main/java/blackjack/domain/game/Hands.java
> +                .filter(((Predicate<? super Card>) AceCard.class::isInstance).negate())
넵 이 부분은 card가 아닌 hands 객체로 역할을 옮겼습니다.

2021-08-30 13:14 UTC, pageprologue commented on src/main/java/blackjack/domain/game/Table.java
> +public class Table {
처음에 테이블 객체를 생성한 이유는 딜러가 참여자이기도 하고, 게임 진행의 역할도 수행하고 있다고 생각해서 그 두가지 역할을 분리하기 위해 생성하였습니다. Table 객체에서는 덱에서 카드를 나눠주는 역할을 하도록 구현 했습니다. 이 부분에 대해서 좀 더 코멘트 주시면 수정해보도록 하겠습니다 :)

2021-08-31 06:15 UTC, pageprologue commented on src/main/java/blackjack/domain/participant/Dealer.java
> +public class Dealer extends Participant {
말씀하신 것 처럼 중복코드가 많아서 상속으로 했었는데요~ 주로 게임 룰에 대한 부분을 공통으로 사용하고 있습니다. 이 부분은 composition 보다는 추상클래스로 하는게 어떨까해서 추상 클래스로 바꿔 보았습니다.

2021-11-05 09:20 UTC, Deocksoo commented
구현하시느라 너무 고생 많으셨습니다 :)

2021-11-05 09:20 UTC, merged