Ariel429
kiworkshop/java-blackjack pull request #4
Opened 2021-07-29 14:22 UTC by Ariel429

<h3>NOTES</h3>

1. Bifunction 적용
    - [API](https://docs.oracle.com/javase/8/docs/api/index.html)
    - [예제](https://jaystevency.tistory.com/9)

2. Map 메서드
    - [computeIfPresent()](https://tinyurl.com/ye5qz95l)
    - [Optional에 대한 null 처리](https://irerin07.tistory.com/108)
    
3. [StringUtils 메서드](https://bigstupid.tistory.com/41)
    - isBlank()
    - isNumericSpace()
    - isAlphaNumericSpace()

4. [문자열 비교](https://eunhee-programming.tistory.com/6)
   - equalsIgnoreCase()
   - compareTo()

5. [ParameterizedTest 사용](https://www.baeldung.com/parameterized-tests-junit-5)
   - @ MethodSource()
   - @ ValueSource()

2021-08-02 15:54 UTC, jjj0611 requested changes
정애 선생님 블랙잭 요구사항 구현해주신 것 잘 봤습니다 :)
아마 블랙잭 룰을 이해하는 것부터 구현하는데까지 쉽지 않으셨을텐데 고생하셨습니다 👍 

몇 가지 고민해볼 것들에 대해서 코멘트 남겼으니 확인 부탁드려요!

더불어 한 가지 말씀드리자면 코드 내에 있는 주석들을 모두 제거해주세요!
코드 내에 주석이 있으면 2가지 문제가 있습니다.
- 주석이 코드 내용을 대체할 수 있습니다.
- 코드가 변경될 때마다 주석을 변경해야 합니다.

즉, 주석의 내용만 보고 코드의 로직을 제대로 보지 않고 지나갈 수 있죠.
물론 추상화를 한다는 것 자체가 로직을 숨기는 것이지만 그것을 주석으로 대체해서는 안됩니다.
또한, 코드가 변경되었는데 주석이 변경되지 않으면 주석만 보고 과거의 동작 방식으로 이해할 수 있습니다.
즉 관리 포인트가 2개가 되는 것이죠.

지금은 코드 내에 모든 주석을 제거하고 최대한 코드만 보고 어떤 내용인지 쉽게 파악할 수 있도록 구현하는데 힘써주세요 :)

2021-08-02 15:54 UTC, jjj0611 commented on README.md
> +        - [x] Ace를 가진 플레이어는 에이스의 숫자값으로 1 혹은 11을 선택할 수 있다.
이 부분에서 ACE라는 카드의 특성과 블랙잭 게임의 특성을 생각해보면 좋을 것 같아요.
정말 플레이어는 1 혹은 11로 선택이 가능할까요?
ACE는 BUST가 되지 않는 합에서는 무조건 11, BUST가 되는 상황이라면 무조건 1로 계산 되어야 하지 않을까요?

10, 10, A의 카드를 가진 사용자 혹은 딜러가 A를 11로 계산하는 경우는 없을거고,
10, A의 카드를 가진 사용자 혹은 딜러가 A를 1로 계산하는 경우는 없을겁니다. 

실제로 BLACKJACK이 되는 경우 사용자에게 카드를 더 받을지 여부를 물어보지 않습니다.

2021-08-02 15:54 UTC, jjj0611 commented on build.gradle
> +    testAnnotationProcessor 'org.projectlombok:lombok:1.18.20'
test에서도 dependency를 추가하신 이유가 있을까요?

추가로 lombok 의존성은 제거하고 구현해주시면 좋을 것 같아요.
lombok 의존성을 제거하고 구현해주세요 :)

2021-08-02 15:54 UTC, jjj0611 commented on src/main/java/blackjack/utils/StringUtil.java
> +        if (!(response.equals("Y") || response.equals("y") || response.equals("N") || response.equals("n"))) {
equals보다 equalsIgnoreCase를 써서 조건을 줄여보면 어떨까요?

2021-08-02 15:54 UTC, jjj0611 commented on src/main/java/blackjack/utils/StringUtil.java
> +    public static String validateYesOrNo(String response) {
이 메서드를 좀 더 짧게 줄일 수 있는 방법은 없을까요?
response가 null이거나 비어있는 것을 체크하고, Y/N 여부를 비교하는 것으로 보이는데,
Y/N 값을 가지고 좀 더 짧게 표현해볼 수 있을 것 같아요!

2021-08-02 15:54 UTC, jjj0611 commented on src/main/java/blackjack/BlackjackApplication.java
> +            e.printStackTrace();
여기서 stackTrace를 출력하는 이유가 있으실까요?

2021-08-02 15:54 UTC, jjj0611 commented on src/main/java/blackjack/controller/BlackJackController.java
> +    private final OutputView outputView = new OutputView();
InputView와 OutputView를 밖에서 주입하지 않고,
내부에서 생성하여 사용하는 이유가 있을까요?

이렇게 사용하게 될 경우 InputView와 OutputView에 종속적인 코드가 되어 변경에 용이하지 않습니다!
controller가 생성될 때 입출력 기능을 하는 view 영역을 주입해주면 view에 종속적이지 않은 코드 작성이 가능할거에요!

2021-08-02 15:54 UTC, jjj0611 commented on src/main/java/blackjack/view/InputView.java
> +        return scanner.nextLine().trim();
StringBuilder를 사용하셨군요! 매우 좋습니다 👍 
그런데 `player.getName() + "는 한장의 카드를 더 받겠습니까"`와 같이 구현하지 않은 이유가 있으실까요?
+가 내부적으로 어떻게 동작하는지, String의 Formmatting 기능을 이용하면 어떻게 작동할까요?

2021-08-02 15:54 UTC, jjj0611 commented on src/main/java/blackjack/view/OutputView.java
> +public class OutputView {
OutputView도 전체적으로 StringBuilder를 사용하셨는데,
가독성을 좀 더 높이는 방향으로 구현해보면 어떨까요?

혹시 StringBuilder를 사용하신 특별한 이유가 있을까요?

2021-08-02 15:54 UTC, jjj0611 commented on src/main/java/blackjack/domain/card/Card.java
> +    }
만약 outputView가 웹에서 표현되는 형태라면 어떨까요?
지금은 현재 toString()이라는 메서드가 console에서 Card를 표현해주는 방식으로만 사용되고 있어요.
만약 console에서 `J하트`가 아닌 `하트J` 와 같이 표현되도록 바뀐다면 어떻게 될까요?

view의 영역에서 변경이 필요한데, domain 객체에서 변경을 해야할 필요성이 생깁니다.
물론 간단한 애플리케이션이므로 toString으로 구현되어도 문제가 없겠지만,
view의 로직은 view의 영역에서 표현되도록 해보면 어떨까요?

2021-08-02 15:54 UTC, jjj0611 commented on src/main/java/blackjack/domain/card/Deck.java
> +    private final List<Card> deck;
test에서만 사용되는 getter인 것 같아요.
test를 위해서 getter를 열어주신 걸까요?

2021-08-02 15:54 UTC, jjj0611 commented on src/main/java/blackjack/domain/card/Denomination.java
> +public enum Denomination {
Denomination이라는 네이밍이 어떤 의미로 사용된걸까요?

2021-08-02 15:54 UTC, jjj0611 commented on src/main/java/blackjack/domain/card/DeckFactory.java
> +    private static List<Card> cardsDeck = createCardsDeck();
createDeck()이라는 메서드에서 return할 값을 미리 생성해두고 사용한 이유가 있을까요?

또한, DeckFactory라는 네이밍이 적절하지 않은 것 같아요.
createDeck()을 했을 때 나오는 return값은 Deck이길 기대하지 않을까요?

List<Card>와 Deck은 동일하다고 할 수 있을까요?
DeckFactory.createDeck();의 return 값으로 List<Card>가 적절할지 Deck이 적절할지 고민해보시면 좋을 것 같아요 :)

2021-08-02 15:54 UTC, jjj0611 commented on src/main/java/blackjack/domain/card/Type.java
> +    }
String type도 모두 view와 관련된 데이터 아닐까요?
만약 `9스페이드`가 아니라 `9SPADE`와 같이 노출되길 원한다면 type에 들어가는 데이터를 SPADE("SPADE")와 같이 변경해주어야 겠군요!

view와 domain을 분리해보는 연습을 해보면 좋을 것 같아요 :)

2021-08-02 15:54 UTC, jjj0611 commented on src/main/java/blackjack/domain/result/Rule.java
> +    DEALER_BUST(((player, dealer) -> dealer.isBust()), WinningResult.WIN),
만약 10번과 11번 라인의 순서가 바뀌면 어떤 일이 일어날까요?
플레이어의 승리 상황이 dealer만 bust되면 되는걸까요?
현재 ENUM의 순서에 따라서 결과를 구하는 방식이 바뀌고 있습니다.

블랙잭 게임에서 플레이어가 bust 되고, 추후에 딜러가 16이하라 카드를 더 받아서 bust되었을 때 돈을 되돌려줄까요?
딜러와 플레이어 모두 bust되는 경우는 누구의 승리인가요?

2021-08-02 15:54 UTC, jjj0611 commented on src/main/java/blackjack/domain/result/Rule.java
> +    TIES(((player, dealer) -> player.getCardsSum() == dealer.getCardsSum()), WinningResult.TIE);
여기서도 PLAYER_HIGHER의 의미는 player와 dealer가 버스트 되지 않은 상태에서의 비교여야 하지 않나요?
PLAYER_HIGHER가 지금 이 Enum 안에서 맨 위로 올라가게 되면,
player 카드의 합이 30이고, dealer 카드의 합이 21이어도, player의 승리로 표현될겁니다.

2021-08-02 15:54 UTC, jjj0611 commented on src/main/java/blackjack/domain/result/GameResult.java
> +    private final Map<WinningResult, Integer> dealerResult = new LinkedHashMap<>();
LinkedHashMap으로 구현하신 이유가 있으실까요?
또한, 이렇게 생성하고 생성자에서 put하는 것보다 생성자에서 할당하는 방식이 더 좋습니다 :)

private final Map<Player, WinningResult> playerResult = new LinkedHashMap<>();

이라고 되어 있으면 저 안에 데이터는 언제 채워지지? 라고 생각이 될텐데

private final Map<Player, WinningResult> playerResult;

로만 되어 있으면 생성하면서 할당해준다는 것이 보여지기 때문에 생성자 로직이 들어가 있는 것을 알 수 있습니다.

2021-08-02 15:54 UTC, jjj0611 commented on src/main/java/blackjack/domain/result/Rule.java
> +public enum Rule {
전체적으로 Rule에 대한 고민을 더 해보시면 좋을 것 같아요.
블랙잭 승리에 대한 고민도 해보시면 좋을 것 같습니다.
지금 Rule의 구조상 딜러는 10, 10, ACE를 갖고 있고,
player는 10, ACE를 가지고 있을 떄도 Tie로 표현이 될텐데,
이는 실제 결과와 상이합니다.

2단계 미션에서 BLACKJACK 승리에 대한 기능 구현이 있지만,
승패 판단에 대한 고민도 다시 해보시면 좋을 것 같습니다 :)

2021-08-02 15:54 UTC, jjj0611 commented on src/main/java/blackjack/domain/participant/Participant.java
> +public abstract class Participant {
participant가 너무 큰 역할을 담당하고 있다고 생각하지 않으시나요?
카드 계산에 대한 로직을 participant 내부에 다 들고 있는것보다
역할을 위임해보면 어떨까요?

한 클래스가 과도한 역할을 지고 있다면 역할을 분리해야할 때일 수 있습니다 :)

2021-08-02 15:54 UTC, jjj0611 commented on src/main/java/blackjack/domain/participant/Player.java
> +    }
ditto

2021-08-02 15:54 UTC, jjj0611 commented on src/main/java/blackjack/domain/participant/Dealer.java
> +    }
test에서만 사용되는 메서드인 것 같아요.
만들어두신 이유가 있을까요?

2021-08-03 10:16 UTC, Ariel429 commented on build.gradle
> +    testAnnotationProcessor 'org.projectlombok:lombok:1.18.20'
lombok을 활용해보자는 의견이 있어서 시도해봤었습니다 ㅎㅎ 제거하고 구현해보겠습니다.

2021-08-03 10:17 UTC, Ariel429 commented on src/main/java/blackjack/utils/StringUtil.java
> +        if (!(response.equals("Y") || response.equals("y") || response.equals("N") || response.equals("n"))) {
Controller isYes()에서만 사용했었는데, 여기서도 활용하면 조건을 줄일 수 있겠네요!
조건 줄여보겠습니다

2021-08-03 10:19 UTC, Ariel429 commented on src/main/java/blackjack/BlackjackApplication.java
> +            e.printStackTrace();
예외처리를 시도해본거라 특별한 이유는 없습니다!

2021-08-03 10:22 UTC, Ariel429 commented on src/main/java/blackjack/domain/card/Denomination.java
> +public enum Denomination {
플레잉 카드의 숫자 1,2,3,4, ... 이 [Denomination](https://ko.wikipedia.org/wiki/%ED%94%8C%EB%A0%88%EC%9E%89_%EC%B9%B4%EB%93%9C)이라고 불린다고 해서 사용했습니다

2021-08-03 10:24 UTC, Ariel429 commented on src/main/java/blackjack/domain/participant/Dealer.java
> +    }
구현과정에서 만들다가 사용한 부분이 지워져서 더이상 필요없게 된 메서드인 듯 합니다. 지우겠습니다 ㅎㅎ

2021-08-03 10:27 UTC, Ariel429 commented on src/main/java/blackjack/domain/result/GameResult.java
> +    private final Map<WinningResult, Integer> dealerResult = new LinkedHashMap<>();
카드 리스트에서 카드를 한장씩 빼더라도 인덱스가 빈 형태가 되지 않게 하려면 LinkedHashMap이 좋을 것 같다고 해서 이렇게 구현했었습니다. 말씀해주신 부분 다시한번 생각해보겠습니다!

2021-08-03 10:29 UTC, Ariel429 commented on src/main/java/blackjack/utils/StringUtil.java
> +    public static String validateYesOrNo(String response) {
isBlank가 없더라도 기대값이 'y', 'n'인것은 동일하니 다시 변경해보겠습니다

2021-08-03 10:31 UTC, Ariel429 commented on src/main/java/blackjack/view/OutputView.java
> +public class OutputView {
printFirstCardsGiven메서드에서 stream을 사용하면서 StringBuilder를 사용했는데, 
String으로 바꿀 수 있는 부분은 바꿔보겠습니다

2021-08-10 11:23 UTC, merged

2021-08-17 17:24 UTC, Ariel429 commented on src/main/java/blackjack/view/InputView.java
> +        return scanner.nextLine().trim();
String의 +연산 또는 concat(), StringBuilder, StringBuffer 의 차이를 찾아보았습니다! 

많은 고민을 하고 사용했던 부분이 아니어서 
바로 아래 질문에 StringBuilder를 사용한 이유를 물으셨을 때 
바꾸겠다고 답을 드렸었는데요. 

String에 + 연산 또는 concat() 사용 시, 
기존의 문자열의 값을 버리고 새로 할당하기에 속도면에서 
성능이 좋지 못하다고 하여 StringBuilder를 사용하는게 더 맞는 것 같다는 생각이 들었습니다. 

StringBuilder를 지양하는 것이 좋겠다고 생각하신다면, 
그 이유나 참고할 수 있는 자료가 어떤 게 있을까요?

2021-08-17 17:32 UTC, Ariel429 commented on src/main/java/blackjack/domain/card/Deck.java
> +    private final List<Card> deck;
미처 정리하지 못한 코드라, 삭제하도록 하겠습니다.

2021-08-17 17:35 UTC, Ariel429 commented on src/main/java/blackjack/domain/participant/Dealer.java
> +    }
구현 마무리 단계에서 미처 정리못한 메서드라, 삭제하도록 하겠습니다.

2021-08-17 17:49 UTC, Ariel429 commented on src/main/java/blackjack/domain/card/Card.java
> +    }
리뷰사항 변경을 하다가 막혀서 질문 드리려고 합니다!

해당 메서드를 아래와 같이 리팩토링 하였는데, 

` public String getCardInfo() {
        return denomination.getDenominationName() + type.getType();
    }
`
이 방식이 toString()을 한 것과 유의미한 차이가 없다고 보여져서 
어떤 방식으로 리팩토링이 진행되어야 한다고 생각하시는지 좀 더 설명해주실 수 있을까요?

2021-08-17 17:55 UTC, Ariel429 commented on src/main/java/blackjack/domain/card/Type.java
> +    }
`9SPADE`가 된다면 출력시에 Type.toString()을 하는 방식으로 적용하면 되지 않을까하고 생각했는데, 

해당 리뷰 주신 내용이 Card 클래스에 사용한 toString()에 대한 리뷰사항과 비슷하게 보여서
view와 domain을 분리하라는 내용을 제가 잘 이해하지 못한 것 같습니다. 

어떤 식으로 하면 좋을지 참고할 자료가 있을까요?

2021-08-17 17:57 UTC, Ariel429 commented on src/main/java/blackjack/domain/participant/Player.java
> +    }
ditto, Player도 Participant처럼 너무 많은 역할을 가지고 있어 책임이 분리되었으면 좋겠다는 말씀이신가요?