블랙잭게임 코드리뷰요청 드립니다.
kiworkshop/java-blackjack pull request #7
Opened 2021-08-04 13:11 UTC by eunii

1. 단축키 보여주는 플러그인
presentation assistant

2. 테스트 클래스 만들어주는 단축키
ctrl shift t test

3. 특정 부분 함수로 빼기
ctrl alt m 함수로 빼기

4. 에러문구 테스트 검사하고싶을때 아래 함수 사용
hasmessage()
withmessage()

5. ctrl + alt +v new 선언하면 자동으로 변수 만들어줌(반환값이 있는 경우)

6. ArrayList 바로 만들기
Array.asList(인자, 인자2)

7. 테스트코드 함수
assertThat(players).hasSize(2)
                .extracting("name") -> 리스트 돌면서 해당 변수 추출
                .contains("pobi", "jason"); -> 해당값을 가지고 있는지 확인

2021-08-08 09:28 UTC, me0768 requested changes
다은선생님 안녕하세요!
여러 요구사항들 맞춰서 구현하시느라 고생많으셨습니다
몇가지 코멘트 남긴것  확인부탁드리고
코멘트에 대한 질문이나 다른 질문들 혹시 있으시면 편하게 주세요:)

2021-08-08 09:28 UTC, myangw commented on src/main/java/blackjack/controller/GameController.java
> +    public void play() {
play()를 호출하는 곳(아마 main메서드)이 없는데 커밋하실때 누락된게 아닌가 싶습니다. 추가해주세요 ㅎㅎ

2021-08-08 09:28 UTC, myangw commented on src/main/java/blackjack/domain/GamePlayerResult.java
> +        this.score = gameService.getCardScore(player);
GameService 클래스 내 메서드에서 GamePlayerResult를 생성하는 부분이 있었는데,
여기서는 GamePlayerResult 클래스를 생성할 때 GameService 객체를 생성하게 되네요. 목적이 있어서 여러개 생성할 필요가 있는 객체가 아닌데 객체 생성하는 코드가 여기저기 있게되면 메모리 이슈가 생길 수 있습니다.

`getCardScore()` 메서드가 필요해서 이렇게 생성하신걸로 추측되는데.. 꼭 service에 두어야할까요? 이 메서드가 하는 행동을 생각하면서 다른 객체에 책임을 부여해보면 어떨까요?

2021-08-08 09:28 UTC, myangw commented on src/main/java/blackjack/domain/GameTotalReuslt.java
> +    int dealerTieCount;
여기 클래스에만 접근제한자가 디폴트인데 따로 이유가 있으신가요?

+)  Reuslt <<  오타인것 같아요

2021-08-08 09:28 UTC, myangw commented on src/main/java/blackjack/domain/Human.java
> +        this("딜러");
딜러 객체가 아닌데 name에 디폴트로 name이 딜러네요. 특별한 이유가 없다면 수정되면 좋겠습니다

2021-08-08 09:28 UTC, myangw commented on src/main/java/blackjack/domain/CardDeck.java
> +        return cards.get(--size);
player나 dealer가 카드를 한장 추가할 때,  card deck에서 전체 카드의 size만 감소시켜주고 실제로 카드는 cards 변수에 다 저장이 되어있는 구조네요. 이렇게 할 경우 size라기보다 카드를 가져올 수 있는 index를 저장하는게 되지 않나 싶습니다.

cards에 그대로 카드가 남아있다는 것을 모르는 다른 사람 또는 미래의 다은님이(??) 이 코드를 유지보수하게된다면 `cards.size()` 함수를 써서 size를 구할 수도 있을텐데 이렇게 하면 항상 size는 전체 카드의 사이즈가 됩니다. 

cards에서 실제적으로 더이상 쓸 수없는 카드는 지우는 작업이 `--size`와 함께 이루어지면 좋겠고, 아니면 size 변수를 따로 선언할 필요가 있는지도 고려해봐주세요.

2021-08-08 09:28 UTC, myangw commented on src/test/java/blackjack/service/GameServiceTest.java
> +        assertThat(playerScore).isEqualTo(8);
dealerScore를 의도하셨던 것 같은데 playerScore로 되어있습니당

수정이 빈번할 때 제출 전에 전체 테스트 돌려보셔서 깨진 테스트 없는지 확인해보세요 ㅎㅎ (test 패키지에서 우클릭하면 전체 돌리는 메뉴가 있습니다)

2021-08-08 09:28 UTC, myangw commented on src/main/java/blackjack/domain/Human.java
> +        return Collections.unmodifiableList(cards);
cards에 외부에서 의도치않게 추가 삭제 될 일 없겠네요 👍

2021-08-08 09:28 UTC, myangw commented on src/main/java/blackjack/domain/CardDeck.java
> +                });
이건 반영 안하셔도 되는데 개인적으로는 이렇게 이중으로 stream으로 forEach도는것보다는 for each문이 가독성있다고 생각해요..

```
for (Denomination cardScore: Denomination.values()) {
           for (Suit cardType : Suit.values()) {
               cards.add(new Card(cardScore, cardType));
           }
        }
```

2021-08-08 09:28 UTC, me0768 commented on src/main/java/blackjack/domain/GamePlayerResult.java
> +        } else {
프로그래밍 요구사항에 else를 쓰지말라는 부분이 있는데요,

GameTotalResult 생성자 부분이랑 같이 개선을 고민해보면 좋겠습니다.

2021-08-10 13:53 UTC, eunii commented on src/main/java/blackjack/controller/GameController.java
> +    public void play() {
넵 main에 넣어서 실행하고 지웠었네요ㅠ 추가했습니다!

2021-08-10 13:53 UTC, eunii commented on src/main/java/blackjack/domain/GamePlayerResult.java
> +        this.score = gameService.getCardScore(player);
해당 기능은 상태패턴으로 변경하면서 player가 가진 상태에 따라 score를 반환하게 변경하였습니다.

2021-08-10 13:56 UTC, eunii commented on src/main/java/blackjack/domain/GameTotalReuslt.java
> +    int dealerTieCount;
접근제어자 추가했습니다. 오타 잡아주셔서 감사해요ㅠ 계속봐도 몰랐었어요.ㅋㅋ수정하였습니다.

2021-08-10 13:57 UTC, eunii commented on src/main/java/blackjack/domain/Human.java
> +        this("딜러");
넵 human을 Participant 객체로 이름 수정 후 dealer 생성자에서 디폴트 이름 넣어주는 것으로 수정하였습니다

2021-08-10 14:02 UTC, eunii commented on src/main/java/blackjack/domain/CardDeck.java
> +        return cards.get(--size);
코멘트 들으니 size()자체는 기본적으로 사용하는 함수라 헷갈릴 수 있을 것 같아서 추천 해주신대로 index 로 변경하였습니다.
card자체를 캐싱해놔서 삭제는 불가능 할것 같은데 queue에 넣는 방법을 2차때 고려해보겠습니다.

2021-08-10 14:02 UTC, eunii commented on src/test/java/blackjack/service/GameServiceTest.java
> +        assertThat(playerScore).isEqualTo(8);
넵 이번엔 다 돌리고 push했습니다!

2021-08-10 14:04 UTC, eunii commented on src/main/java/blackjack/domain/CardDeck.java
> +                });
이 부분은  indent(인덴트, 들여쓰기) depth2 단계 조건때문에 스트림으로 해놨는데요.  조금더 가독성을 높이는 방법을 고민해보겠습니다.

2021-08-10 14:05 UTC, eunii commented on src/main/java/blackjack/domain/GamePlayerResult.java
> +        } else {
넵 해당 부분은 if 절로 리턴해주는 방법으로 수정하였습니다

2021-08-10 14:55 UTC, merged