블랙잭 게임 2단계 리뷰 요청 드립니다.
kiworkshop/java-blackjack pull request #8
Opened 2021-08-05 11:12 UTC by jiwoo-kimm

안녕하세요 우빈 선생님!
블랙잭 게임 2단계 리뷰 부탁드립니다~

2021-08-09 12:30 UTC, wbluke requested changes
2단계도 깔끔하게 잘 구현해 주셨네요 👍 
이전에 구조가 잘 잡혀 있어서 그런지 큰 무리 없이 기능을 추가한 것으로 보이네요 ㅎㅎ
소소한 코멘트 몇 개 남겼으니 확인 부탁드려요 🙂

2021-08-09 12:30 UTC, wbluke commented on src/main/java/blackjack/domain/participant/Players.java
> +        this.players = Collections.unmodifiableList(new ArrayList<>(players));
방어 로직 잘 작성해 주셨네요 👍

2021-08-09 12:30 UTC, wbluke commented on src/main/java/blackjack/domain/game/Table.java
>          }
```java
while (dealer.hit()) {
    hit(dealer);
}
```
메서드 형태만 봐서는 어떤 일을 하고 있는지 잘 모를 것 같아요 ㅎㅎ
dealer.hit() 과 hit(dealer) 의 차이가 무엇인지?
메서드명을 자연스럽게 수정해볼 수 있을까요? :)

2021-08-09 12:30 UTC, wbluke commented on src/main/java/blackjack/domain/prize/PlayersPrize.java
> +        return playersPrize;
stream 사용해봐도 되겠네요 :)

2021-08-09 12:30 UTC, wbluke commented on src/main/java/blackjack/domain/prize/Prize.java
> +    private final double multiple;
요 필드명이 잘 와닿진 않네요. 배당률? 이라고 하면 어떨까요?
`dividendRate`

2021-08-09 12:30 UTC, wbluke commented on src/main/java/blackjack/domain/prize/Prize.java
> +        final HandsStatus playerStatus = HandsStatus.of(player);
(이 코멘트는 개인적인 생각입니다. 참고만 해주세요 !)
곳곳에서 로컬변수에 final 처리를 해주셨는데, 저는 로컬변수와 파라미터에 final 처리를 하는 방식이 크게 효과가 없다고 생각하고 있어요 ㅎㅎ
- 클린코드를 지향하면 메서드를 잘게 쪼개게 되는데, 메서드 길이가 짧아질수록 로컬변수나 파라미터가 변경될 확률은 매우 낮아진다.
- 로컬변수나 파라미터가 변경될 것을 대비해 방지하는 효과보다, 모든 선언에 final을 붙임으로써 가독성을 떨어뜨리는 역효과가 조금 더 크다.(고 생각)

하지만 취향의 문제도 있을 수 있음을 충분히 고려하고 있습니다 :)

2021-08-09 12:30 UTC, wbluke commented on src/main/java/blackjack/domain/prize/Prize.java
> +        return findPlayerPrizeOnHold(player, dealer);
블랙잭에서 참 고민되는 부분 중 하나죠. 
어디선가 if문이 반복되면 본능적으로 `어떻게든 추상화시켜서 if문의 향연을 없앨 수 있지 않을까?` 라는 생각이 들기 마련인데
블랙잭의 이 부분은 Case by Case 로 접근할 수 밖에 없는 것 같은 애매함만 있어서 좋은 방법이 떠오르진 않고 답답하기만 합니다 ㅋㅋ

2021-08-10 05:48 UTC, jiwoo-kimm commented on src/main/java/blackjack/domain/game/Table.java
>          }
넵 `dealer.hit()`을 `dealer.needMoreCard()`로 수정해봤어요!

2021-08-10 05:50 UTC, jiwoo-kimm commented on src/main/java/blackjack/domain/prize/PlayersPrize.java
> +        return playersPrize;
아 넵! stream으로 수정했습니다

2021-08-10 05:51 UTC, jiwoo-kimm commented on src/main/java/blackjack/domain/prize/Prize.java
> +    private final double multiple;
아 네 그게 더 좋네요! 수정했습니다

2021-08-10 06:14 UTC, jiwoo-kimm commented on src/main/java/blackjack/domain/prize/Prize.java
> +        final HandsStatus playerStatus = HandsStatus.of(player);
아하 넵! 그러네요

저 메서드 작성할 때, status가 계속 파라미터로 다른 메서드로 전달이 되니까,
이 과정에서 문제가 생길 수도 있으니 final로 불변 처리를 하는게 좋겠다는 생각이 들었어요
그치만 말씀하신대로 변경될 확률 자체가 적으니 굳이 하지 않아도 되겠네요!
지금은 이 메서드랑 `PlayersPrize`에서만 지역변수에 final을 사용했는데, 통일성도 떨어지는 것 같고요..

아무튼 다 제거하는 방향으로 수정했습니다!

2021-08-10 06:15 UTC, jiwoo-kimm commented on src/main/java/blackjack/domain/prize/Prize.java
> +        return findPlayerPrizeOnHold(player, dealer);
네.. 보기만해도 속이 답답해지는 부분인데, 상태 체크 후 결과를 도출하는 로직이 어딘가에는 꼭 있어야 하니 그대로 유지했습니다 😂

2021-08-11 05:30 UTC, jiwoo-kimm commented
말씀해주신 부분들 수정했습니다!
그리고 스터디 모임 시간에 얘기 나왔던 부분들 중심으로 몇 가지 추가로 리팩토링을 더 해봤는데요,

1. `Card` 캐싱
2. `BettingTable`, `prize`, `profit` 로직 분리
    - `PlayersPrize`에서 플레이어 승패 결과 매핑
    - `BettingTable`에서 플레이어 베팅 금액 매핑
    - `PlayersProfit`은 최종 결과값 출력에 사용되기 때문에 내부적으로 `playerName`을 필드로 갖고 있고, Map이 아니라 List로 관리
3. Custom Exception 적용해서 예외처리 리팩토링

이 부분들 중심으로 리뷰 해주시면 감사하겠습니다!

2021-08-13 12:42 UTC, wbluke requested changes
수정 잘 해주시고, 추가적인 리팩토링까지 잘 진행해주셨네요 ㅎㅎ
테스트도 정말 꼼꼼하게 작성해주셔서 놀랐습니다 👍 (93개라니..)
새로 추가하신 부분과 테스트에 관련하여 몇 가지 코멘트를 좀 더 남겼는데요 ㅎㅎ 확인 부탁드려요 🙂

2021-08-13 12:42 UTC, wbluke commented on src/main/java/blackjack/domain/card/Card.java
>          this(suit, MAJOR_CARD_RANK, signature);
다시 보니 이 생성자는 내용이 MAJOR_CARD 에 대한 생성자인데, 생성자 자체에는 그런 정보가 없네요.
정적 팩토리 메서드로 의미를 담으면 좋을 것 같아요 :)

2021-08-13 12:42 UTC, wbluke commented on src/main/java/blackjack/domain/card/Card.java
> +    }
Suit처럼 Signature도 Enum으로 관리한 뒤에 이 로직을 리팩토링해보면 어떨까요?
Signature : ("A", 11), ("2", 2), ("3", 3), ... , ("Q", 10), ("K", 10); rank랑 묶어서 이런 형태가 될 것 같고
그에 따라 모든 카드를 생성하는 방식이 훨씬 간단해질 것 같아요 :)

2021-08-13 12:42 UTC, wbluke commented on src/main/java/blackjack/domain/card/Card.java
> +    }
현재 AceCard도 실제 Card와 연관이 있다기 보다는 `에이스 카드의 정보들만 가진 어떤 객체` 로 보이는데요.
Signature를 만들면서 좀 더 Card와 관련이 있게 가져가봐도 좋지 않을까요? :)

2021-08-13 12:42 UTC, wbluke commented on src/main/java/blackjack/domain/card/Card.java
> +    public static Card get(Suit suit, String signature) {
내부적으로 get이긴 하지만, 외부에서는 모르는 행위고, 인스턴스를 생성하는 정적 팩토리 메서드이기 때문에 `of` 같은 네이밍이 더 나을 것 같아요 :)

2021-08-13 12:42 UTC, wbluke commented on src/main/java/blackjack/domain/profit/PlayersProfit.java
> +                        prizes.getPrize(playerName)))
생성 부분을 한번 더 메서드로 빼도 좋을 것 같네요 :)

2021-08-13 12:42 UTC, wbluke commented on src/main/java/blackjack/exception/NoSuchCardException.java
> +    private static final String NO_SUCH_CARD = "매칭되는 카드가 없습니다.";
custom exception 사용 좋네요 👍

2021-08-13 12:42 UTC, wbluke commented on src/main/java/blackjack/view/InputView.java
> +        if (Objects.isNull(input) || input.isEmpty()) {
개인적으로는 input == null 이 더 명확해보이긴 해요 ㅎㅎ
Objects.isNull 은 보다 덜 직관적이기도 하고(한번 더 해석을 해야하는), 
stream에서의 사용을 위한 Predicate 긴 하거든요 :)

2021-08-13 12:42 UTC, wbluke commented on src/test/java/blackjack/domain/profit/PlayersProfitTest.java
> +        assertThat(profits.get(2).getPlayerName()).isEqualTo("c");
```suggestion
        assertThat(profits).hasSize(3)
                .extracting("playerName")
                .containsExactly("a", "b", "c");
```
요렇게 할 수 있어요 :)
(순서가 상관 없는 검증이라면 `containsExactlyInAnyOrder` 를 사용할 수도 있구요.
검증할 값이 여러 개라면 `tuple`을 사용할 수도 있어요. 한번 찾아보시면 좋을 것 같아요 ㅎㅎ)

2021-08-13 12:42 UTC, wbluke commented on src/test/java/blackjack/domain/profit/PlayersProfitTest.java
> +        PlayersPrize playersPrize = generatePlayersPrize();
테스트할 항목과 직접적으로 연관되어 있는 given 데이터는 private 메서드로 중복을 제거하는 것이 오히려 테스트 내용에 대한 명세를 방해한다고 생각해요 ㅎㅎ
지금 같은 경우는 given 절에서 어떤 데이터를 생성했는지 아래에 있는 private 메서드를 찾아봐야만 하는데요.
테스트마다 같은 내용이더라도 정확하게 지금 어떤 테스트를 위해 데이터를 준비하고 있는지를 보여주면 좋겠습니다.
각 테스트가 모두 별도의 문서라고 생각해보시면 이해가 되실 거에요 ㅎㅎ

(단, 정말로 직접적인 연관이 없고, fixture를 준비하기 위한 사전 작업이라면 (= 해당 테스트에서 구체적인 내용을 알 필요가 없는 준비단계라면) private 메서드나 beforeEach 단계로 뽑을 수 있겠습니다 :) )

2021-08-13 12:42 UTC, wbluke commented on src/test/java/blackjack/domain/profit/PlayersProfitTest.java
> +        PlayersPrize playersPrize = generatePlayersPrize();
테스트에서는 약간의 중복이 발생하거나 메서드 길이가 길어지더라도, `애플리케이션 명세` 라는 더 상위의 목적을 생각하면서 작성해보시면 좋을 것 같아요 :)

2021-08-14 08:54 UTC, jiwoo-kimm commented on src/main/java/blackjack/domain/card/Card.java
>          this(suit, MAJOR_CARD_RANK, signature);
넵 정적 팩토리 메서드로 수정했습니다!

2021-08-14 08:55 UTC, jiwoo-kimm commented on src/main/java/blackjack/domain/card/Card.java
> +    public static Card get(Suit suit, String signature) {
넵 정적 팩토리 메서드 네이밍 컨벤션 반영했습니다!

2021-08-14 09:28 UTC, jiwoo-kimm commented on src/main/java/blackjack/view/InputView.java
> +        if (Objects.isNull(input) || input.isEmpty()) {
아하 넵! Predicate로 쓰려고 만들어진 메서드인건 몰랐네요! 이렇게 또 하나 배워갑니다..

2021-08-14 10:08 UTC, jiwoo-kimm commented on src/main/java/blackjack/domain/card/Card.java
> +    }
넵 `Signature` Enum 클래스로 새로 만들어서 리팩토링 해봤습니다!
더불어 `AceCard`도 `Signature` 안으로 편입시켜봤어요

그런데 `sumAceCards()`가 `Hands`가 아닌 `Signatrue`에 있어도 되는 건지 확신이 안서네요...
`Signature`에다가 에이스 카드들의 합을 구하는 기능만 따로 분리한 이유는
1. `sumAceCards()` 테스트가 용이하다. 만약 `Hands`로 옮기면 이 세부 기능만 테스트하기 애매해지고, 카드 파라미터를 복잡하게 만들어서 넘겨야만 테스트할 수 있게 된다.
2. `SOFT_RANK`, `HARD_RANK` 값을 노출시키지 않고 내부적으로 결정해서 결과값만 반환할 수 있다.

이렇게 두 가지인데,  사실 카드 여러 장을 관리하고 모두 알고 있는 객체는 `Hands`라서, `Signature`한테 이 역할을 부여해도 되는지 잘 모르겠어요..! 어느 쪽이 더 나은 선택인지 조언 주실 수 있으실까요??

2021-08-14 10:11 UTC, jiwoo-kimm commented on src/main/java/blackjack/domain/profit/PlayersProfit.java
> +                        prizes.getPrize(playerName)))
넵 수정했습니다!

2021-08-14 10:32 UTC, jiwoo-kimm commented on src/test/java/blackjack/domain/profit/PlayersProfitTest.java
> +        assertThat(profits.get(2).getPlayerName()).isEqualTo("c");
오 `AssertJ`에 유용한 메서드들이 많네요! 감사합니당

2021-08-14 10:58 UTC, jiwoo-kimm commented on src/test/java/blackjack/domain/profit/PlayersProfitTest.java
> +        PlayersPrize playersPrize = generatePlayersPrize();
네넵 알겠습니다! 테스트 메서드 쭉 검토하면서 목적에 맞게 리팩토링해봤어요!

2021-08-15 11:42 UTC, wbluke approved these changes
피드백 반영 감사합니다 !
남겨주신 질문에 대한 답변은 코멘트로 드렸고요, 블랙잭 미션 고생 많으셨어요 🙂

2021-08-15 11:42 UTC, wbluke commented on src/main/java/blackjack/domain/card/Signature.java
> +    }
이 메서드들은 정적 메서드가 아니라 멤버 메서드여도 되지 않을까요? :)
```java
public boolean isAce() {
    return this == ACE;
}
```

2021-08-15 11:42 UTC, wbluke commented on src/main/java/blackjack/domain/card/Card.java
> +                        .forEach(signature -> CARD_CACHE.put(generateKey(suit, signature.getSymbol()), new Card(suit, signature))));
와! 초기화 로직이 엄청 깔끔해졌네요 👍

2021-08-15 11:42 UTC, wbluke commented on src/main/java/blackjack/domain/card/Signature.java
> +    }
> 그런데 sumAceCards()가 Hands가 아닌 Signatrue에 있어도 되는 건지 확신이 안서네요...
Signature에다가 에이스 카드들의 합을 구하는 기능만 따로 분리한 이유는
> 
> sumAceCards() 테스트가 용이하다. 만약 Hands로 옮기면 이 세부 기능만 테스트하기 애매해지고, 카드 파라미터를 복잡하게 만들어서 넘겨야만 테스트할 수 있게 된다.
SOFT_RANK, HARD_RANK 값을 노출시키지 않고 내부적으로 결정해서 결과값만 반환할 수 있다.
이렇게 두 가지인데, 사실 카드 여러 장을 관리하고 모두 알고 있는 객체는 Hands라서, Signature한테 이 역할을 부여해도 되는지 잘 모르겠어요..! 어느 쪽이 더 나은 선택인지 조언 주실 수 있으실까요??

오 네 저는 Hands에 있는 게 더 맞는 것 같아요!
에이스 카드를 어떻게 사용할지(1 or 11)는 Signature를 사용하는 클라이언트 쪽에서 판단해야 할 문제라고 생각해요.
Signature 쪽에서는 다음과 같이 HardRank에 대한 메서드를 제공하기만 하면 되지 않을까 합니다 :)

```java
public int getHardRank() {
    if (this != ACE) {
        throw new UnsupportedOperationException(String.format("Hard rank는 ACE만 보유하고 있습니다. CARD=%s", this.name()));
    }
    return HARD_RANK;
}

// 아니면 간단하게
public int getAceHardRank() {
    return HARD_RANK;
}
```

2021-08-15 11:42 UTC, wbluke commented on src/main/java/blackjack/domain/card/Signature.java
> +    private static final int SOFT_RANK = 11;
네이밍에 ACE가 들어가면 좋을 것 같아요 ㅎㅎ (`ACE_HARD_RANK` 또는 `HARD_RANK_OF_ACE`)

2021-08-15 11:42 UTC, wbluke commented on src/main/java/blackjack/view/OutputView.java
> +                .map(card -> card.getSymbol() + card.getSuit().getName())
```suggestion
                .map(card -> card.getSymbol() + card.getSuitName())
```
요렇게 해주면 조금 더 깔끔하겠네요 :)

2021-08-15 11:42 UTC, wbluke commented on src/test/java/blackjack/domain/profit/PlayersProfitTest.java
> +        );
각 테스트의 흐름과 내용이 훨씬 읽기 좋아졌네요 👍

2021-08-15 11:42 UTC, merged

2021-08-16 03:06 UTC, jiwoo-kimm commented on src/main/java/blackjack/domain/card/Signature.java
> +    }
아 네 그러네요! 메서드 옮길 때 깜빡했습니다ㅎㅎ;

2021-08-16 03:09 UTC, jiwoo-kimm commented on src/main/java/blackjack/view/OutputView.java
> +                .map(card -> card.getSymbol() + card.getSuit().getName())
넵 그러네요!

2021-08-16 03:10 UTC, jiwoo-kimm commented on src/main/java/blackjack/domain/card/Signature.java
> +    private static final int SOFT_RANK = 11;
아 넵! 알겠습니다

2021-08-16 03:15 UTC, jiwoo-kimm commented on src/main/java/blackjack/domain/card/Signature.java
> +    }
아하 넵 알겠습니다! 
ACE의 Rank 상수를 public으로 노출하지 않고 저렇게 인스턴스 메서드로 호출할 수도 있군요... 저렇게 해보겠습니다!!